# Generated by Django 4.0 on 2022-07-29 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_bookings_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
