# Generated by Django 4.0 on 2022-08-30 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_bookings_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Premium', 'Premium')], default='None', max_length=100),
        ),
    ]
