# Generated by Django 4.0 on 2022-09-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_remove_profile_mood_bookings_stats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Premium', 'Premium'), ('Admin', 'Admin')], default='Normal', max_length=100),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
